export const DEFERRED_SOURCE_MODULES = [
  'src/components/app/StorageRecovery.tsx',
  'src/lib/storage-recovery.ts',
  'src/lib/storage-recovery-actions.ts',
  'src/components/CollectionExtras.tsx',
  'src/components/RatingsTable.tsx',
  'src/components/catalog/ExtendedResults.tsx',
  'src/lib/discovery-catalog.ts',
  'src/lib/saved-discovery-artwork.ts',
  'src/components/CollectionFilms.tsx',
  'src/components/scene/ArtifactStill.tsx',
  'src/components/AboutDialog.tsx',
  'src/components/SettingsDialog.tsx',
  'src/components/personal/BackupPanel.tsx',
  'src/components/PwaControls.tsx',
  'src/components/app/SettingsPanel.tsx',
  'src/pwa/client.ts',
  'src/pwa/client-entry.ts',
] as const;
