import { Dialog } from './Dialog';
import { Icon } from './Icon';
import { author } from '../lib/author';

export function AboutDialog({ onClose, getReturnFocus }: { onClose: () => void; getReturnFocus?: () => HTMLElement | null }) {
  return (
    <Dialog open titleId="about-title" onClose={onClose} getReturnFocus={getReturnFocus} className="info-dialog" motion={{ preset: 'dialog', enterMs: 160 }}>
      <h2 id="about-title" data-autofocus tabIndex={-1}>About Play 100</h2>
      <p className="dialog-lead">A personal collection of 100 games, not an official best-games ranking.</p>
      <section><h3>Original order</h3><p>The <strong>Core 50</strong> are ranks 1-50. The <strong>Essential 50</strong> are ranks 51-100. Both follow the original workbook's main sheet, including its manual changes. Sorting this website never changes those original ranks.</p></section>
      <section><h3>Author ratings</h3><p>These are {author.fullName}'s original workbook scores, based on each game's rank. The source column is headed "my rating(based on rank)". Cards, the table and game details show those saved values, including rounded or text-based results, rather than recalculating them.</p><p>For example, The Witcher 3's original value is 9.9, and Grand Theft Auto IV's is 9.8. Source notes remain attached. Your editable personal ratings are separate and are never prefilled from {author.shortName}'s ratings.</p></section>
      <section><h3>Critic scores</h3><p>Critic scores were carried over from the supplied workbook. They are not live, newly researched or independently verified. Metacritic and PC Gamer use 100-point scales; IGN and GameSpot use 10.</p><p>The critic average normalizes available scores to 100 and averages the entered columns. Both Metacritic columns count when present; missing scores do not. This is not an official aggregate or a count of independent publications.</p></section>
      <section><h3>Source notes &amp; artwork</h3><p>Some entries explicitly include an AI / not-played source note. Those notes are preserved in game details. The absence of a note does not mean a game was played. Every visitor starts with an empty personal list.</p><p>The original scope excludes Nintendo and retains the premium non-AAA exceptions already in the source. No new platform availability, playtimes or scores have been invented.</p><p>The supplied covers are small thumbnails, not high-resolution artwork. We keep their native size within original collection frames. Rank 73 preserves the source's "Hitman: World of Assassination" title, 2016 year and HITMAN III-branded cover; packaging does not establish an exact edition or platform.</p></section>
      <section><h3>Data &amp; privacy</h3><p>Guest games, progress, ratings and notes stay in this browser's IndexedDB. Optional Google or verified email accounts use Firebase Authentication and Firestore on the no-cost Spark plan. Signing in does not automatically upload the guest library; online saving requires a separate choice and consent. Each account has a separate local cache.</p><p>Before online saving, you agree that the creator can view your account profile and ranking summary. Private notes and queues are not loaded in that creator view, but a database operator can technically access stored data. The app does not use Supabase, analytics scripts, ad trackers, anonymous account creation or remote avatar services.</p><p>Private rankings may include games you have not played. Ranking never marks a game played or completed. Explicitly published snapshots contain only the previewed profile and selected game ratings; email, notes and play history are excluded. Community listing is a separate opt-in. Link-only is still public to anyone with the link.</p><p>Settings supports backup export/import and browser eviction protection. Clearing site data can erase unsynced local edits. Free cloud quotas can pause online saving; errors and conflicts do not silently replace a local copy. Account offers sign-out, stopping sync, export and deletion; minimal content-free revocation markers prevent stale tabs from recreating deleted data.</p></section>
      <section><h3>Public catalogs</h3><p>Discover queries public game metadata from <a href="https://www.wikidata.org/wiki/Wikidata:Data_access" target="_blank" rel="noreferrer">Wikidata (CC0)</a> and the documented <a href="https://www.freetogame.com/api-doc" target="_blank" rel="noreferrer">FreeToGame API</a>. Game data from <a href="https://www.freetogame.com/" target="_blank" rel="noreferrer">FreeToGame</a> is attributed and linked to its source.</p><p>Catalog lookup sends your search query to a small read-only proxy and the selected provider. It does not send your private library, notes or rankings. Pages load only when requested. Wikidata coverage is limited to entries explicitly classified as video games; FreeToGame covers its free-to-play catalog. Neither is a complete inventory of every game ever made.</p><p>We import factual metadata, not external cover artwork, descriptions, prices or review scores. Source dates can describe a particular edition rather than the first release everywhere. No accounts or API keys are required, and unavailable sources show an error rather than an empty success. You can also add your own game title manually.</p></section>
      <section className="credits"><h3>Sources &amp; credits</h3><p>Source: <span className="source-filename">AAA_games_u_have_to_play_list_top_100.xlsx</span>, main tab "AAA Top 50" (which actually contains 100 entries). The enhanced download reconciles the derived sheets to that source. The untouched original is also downloadable; its older derivative tabs are not the authoritative order.</p><p>All 100 cover images were supplied in the workbook; artwork rights remain with their respective owners. Fallback game jackets and the folding 3D collection are original supporting artwork, not official game covers.</p><p>Built with React, Three.js, dnd kit, native IndexedDB and customized <a href="https://reactbits.dev" target="_blank" rel="noreferrer">React Bits</a> CountUp, Magnet and AnimatedContent. React Bits copyright 2026 David Haz, used under its MIT + Commons Clause license. Typography: Barlow Condensed and Hanken Grotesk, under the SIL Open Font License. Creature avatars use locally generated DiceBear Critters (CC0 1.0) with DiceBear core (MIT); no Google photo is fetched.</p><a className="text-button" href="/licenses/dicebear.txt" target="_blank" rel="noreferrer">Creature avatar notices<Icon name="up-right" width="17" height="17" /></a><a className="text-button" href="/credits.txt" target="_blank" rel="noreferrer">Read third-party notices<Icon name="up-right" width="17" height="17" /></a></section>
    </Dialog>
  );
}
