import { Dialog } from './Dialog';
import { Icon } from './Icon';
import { author } from '../lib/author';

export function AboutDialog({ onClose }: { onClose: () => void }) {
  return (
    <Dialog open titleId="about-title" onClose={onClose} className="info-dialog">
      <h2 id="about-title" data-autofocus tabIndex={-1}>A collection.<br />Not a consensus.</h2>
      <p className="dialog-lead">A hundred games, arranged with a point of view. This is a personal curated list, not an official ranking of the greatest games ever made.</p>
      <section><h3>One order. Two chapters.</h3><p>The <strong>Core 50</strong> are ranks 1-50. The <strong>Essential 50</strong> are ranks 51-100. Both follow the original workbook's main sheet, including its manual changes. Sorting this website never changes those original ranks.</p></section>
      <section><h3>{author.shortName}'s original ratings, clearly his.</h3><p>The original workbook contains {author.fullName}'s own rating column, headed "my rating(based on rank)". Those original cached ratings are shown by default on cards, in the table and in game details. Their rank-based origin is preserved; we do not replace rounded or text-based source values with a reconstructed curve.</p><p>For example, The Witcher 3's original value is 9.9, and Grand Theft Auto IV's is 9.8. Source notes remain attached. Your editable device-only ratings are a separate feature: they are never prefilled from {author.shortName}'s ratings.</p></section>
      <section><h3>Critics are a separate snapshot.</h3><p>Critic scores were carried over from the supplied workbook. They are not live, newly researched or independently verified. Metacritic and PC Gamer use 100-point scales; IGN and GameSpot use 10.</p><p>The critic average normalizes available scores to 100 and averages the entered columns. Both Metacritic columns count when present; missing scores do not. This is not an official aggregate or a count of independent publications.</p></section>
      <section><h3>What the source does, and doesn't, say.</h3><p>Some entries explicitly include an AI / not-played source note. Those notes are preserved in game details. The absence of a note does not mean a game was played. Every visitor starts with an empty personal list.</p><p>The original scope excludes Nintendo and retains the premium non-AAA exceptions already in the source. No new platform availability, playtimes or scores have been invented.</p><p>The supplied covers are small thumbnails, not high-resolution artwork. We keep their native size within original collection frames. Rank 73 preserves the source's "Hitman: World of Assassination" title, 2016 year and HITMAN III-branded cover; packaging does not establish an exact edition or platform.</p></section>
      <section><h3>Your list is yours. On this device.</h3><p>Your play queue, imported games, completion history, personal rankings, scores and notes are saved in this browser's IndexedDB. Existing Play 100 browser lists migrate automatically. There are no accounts, tracking scripts, analytics, Supabase connections or server-side personal profiles.</p><p>Private rankings may include games you have not played. Ranking a game does not mark it played or completed. Completed favorites can remain in your play queue for a replay, and personal order never changes the author's 100.</p><p>Use Settings to export a complete JSON backup, import it on another browser, or request browser eviction protection. Manually clearing site data can still remove your library. Shared collection links include public choices and filters, not your saved progress or private rankings.</p></section>
      <section><h3>A bigger catalog, without a mass crawler.</h3><p>Discover queries public game metadata from <a href="https://www.wikidata.org/wiki/Wikidata:Data_access" target="_blank" rel="noreferrer">Wikidata (CC0)</a> and the documented <a href="https://www.freetogame.com/api-doc" target="_blank" rel="noreferrer">FreeToGame API</a>. Game data from <a href="https://www.freetogame.com/" target="_blank" rel="noreferrer">FreeToGame</a> is attributed and linked to its source.</p><p>Catalog lookup sends your search query to a small read-only proxy and the selected provider. It does not send your private library, notes or rankings. Pages load only when requested. Wikidata coverage is limited to entries explicitly classified as video games; FreeToGame covers its free-to-play catalog. Neither is a complete inventory of every game ever made.</p><p>We import factual metadata, not external cover artwork, descriptions, prices or review scores. Source dates can describe a particular edition rather than the first release everywhere. No accounts or API keys are required, and unavailable sources show an error rather than an empty success. You can also add your own game title manually.</p></section>
      <section className="credits"><h3>Source &amp; craft</h3><p>Source: <span className="source-filename">AAA_games_u_have_to_play_list_top_100.xlsx</span>, main tab "AAA Top 50" (which actually contains 100 entries). The enhanced download reconciles the derived sheets to that source. The untouched original is also downloadable; its older derivative tabs are not the authoritative order.</p><p>All 100 cover images were supplied in the workbook; artwork rights remain with their respective owners. Fallback game jackets and the folding 3D collection are original supporting artwork, not official game covers.</p><p>Built with React, Three.js, dnd kit, native IndexedDB and customized <a href="https://reactbits.dev" target="_blank" rel="noreferrer">React Bits</a> CountUp, Magnet and AnimatedContent. React Bits copyright 2026 David Haz, used under its MIT + Commons Clause license. Typography: Barlow Condensed and Hanken Grotesk, under the SIL Open Font License.</p><a className="text-button" href="/credits.txt" target="_blank" rel="noreferrer">Read third-party notices<Icon name="up-right" width="17" height="17" /></a></section>
    </Dialog>
  );
}
